### ISSUE TITLE
IEEE xxx 期刊的缩写大小写错误

### ISSUE THREAD

**Issue by S-Kee** [zoushucai/zotero-journalabbr#1]
IEEE系列期刊 缩写中IEEE应该还是大写，但是软件输出的是Ieee

**Comment by zoushucai** [comment]
> Ieee

这个源文件都是那样， 我只是把别人的弄过来了， 感觉没有必要更改源文件。[JabRef/abbrv.jabref.org](https://github.com/JabRef/abbrv.jabref.org)
