### ISSUE TITLE
Zotero会议怎么添加缩写

### ISSUE THREAD

**Issue by sliu7102** [zoushucai/zotero-journalabbr#10]
Zotero中的会议怎么添加缩写？

**Comment by zoushucai** [comment]
> Zotero中的会议怎么添加缩写？

感觉和期刊一样呀... 如果遇到问题,可以给一个简单的案例吗?

**Comment by sliu7102** [comment]
感谢您的及时回复以及您的项目，很好地解决了zotero中期刊缩写的问题。
我没弄明白的地方在于条目类型为"会议论文"的项目，没有像期刊类型的“刊名简称”这一缩写欸，导致在导出引文（我一般手动导出，右键“用所选条目创建参考文献”）的时候还是会议全称。
在使用插件更新“会议论文”的实现显示没有更新，但没有报错，“一步更新”反馈为：
不知道您是怎么解决的，请指教下。感谢~·










在 2023-06-03 00:18:28，"zoushucai" ***@***.***> 写道：

Zotero中的会议怎么添加缩写？

感觉和期刊一样呀... 如果遇到问题,可以给一个简单的案例吗?

**Comment by zoushucai** [comment]
@sliu7102  不好意思, 这个插件解决不了这个问题, 我才想到,我开始制作这个插件时, 并没有考虑到会议论文和学位论文的简写,因为 zotero 软件本身都没有对会议论文和学位论文的期刊名(表达不是很准确)标注简写字段, 所以就没考虑

**Comment by sliu7102** [comment]
OKK，已经挺好了，感谢
