### ISSUE TITLE
插件自动更新不生效

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [zoushucai/zotero-journalabbr#11]
大佬，zotero-journalabbr插件自动更新不生效。win10端，zotero6.0.26版，zotero-journalabbr插件自动更新已打开，但是检测插件更新时，没有更新提示，每次只能手动进入github下载最新插件

**Comment by zoushucai** [comment]
我不是大佬，学生一枚，造成这个原因可能是，某个版本（好像是0.6.3）测试的时候，忘记更新版本就提交了，最近的几个版本应该没问题，我测试了一下，从0.6.9和0.6.4到最新版没问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月6日(周二) 上午10:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zoushucai/zotero-journalabbr] 插件自动更新不生效 (Issue #11)




 
大佬，zotero-journalabbr插件自动更新不生效。win10端，zotero6.0.26版，zotero-journalabbr插件自动更新已打开，但是检测插件更新时，没有更新提示，每次只能手动进入github下载最新插件
