### ISSUE TITLE
zotero7 beta 15版本，插件设置页面是空白

### ISSUE THREAD

**Issue by jlu511** [zoushucai/zotero-journalabbr#12]
![image](https://github.com/zoushucai/zotero-journalabbr/assets/64378673/f3415804-bb69-4e7a-abc4-053c8e54ad33)

**Comment by zoushucai** [comment]
@jlu511  是呀, 因为没有适配 zotero7, 等版本稳定了再说

**Comment by jlu511** [comment]
哦，好的
