### ISSUE TITLE
会议缩写

### ISSUE THREAD

**Issue by zhousodo** [zoushucai/zotero-journalabbr#13]
可否考虑，整理IEEE会议缩写文件，或者单独存放csv 文件。市面上都无法对会议缩写进行操作，从而无法使用green fog 进行会议分区查询，给科研带来许多烦恼？您的插件恰好可以做这件事情，相信这是很多人的需求， ^_^

**Comment by zoushucai** [comment]
@zhousodo 您说的是 `会议`字段这个吗? 还是指的是期刊中的 IEEE 会议?

**Comment by zhousodo** [comment]
IEEE 发布的会议论文， 例如“Proceedings of the 2006 conference on Applications, technologies, architectures, and protocols for computer communications”  （缩写为SIGCOMM '06） 这样的会议名称， 可能是因为期刊的缩写问题或者其他问题导致绿青蛙无法准确的抓取到，所以不能显示分区操作。

**Comment by zhousodo** [comment]
IEEE 发布的会议论文， 例如“Proceedings of the 2006 conference on Applications, technologies, architectures, and protocols for computer communications”  （缩写为SIGCOMM '06） 这样的会议名称， 可能是因为期刊的缩写问题导致绿青蛙无法准确的抓取到，所以不能显示分区操作。

**Comment by zoushucai** [comment]
比如:  https://dl.acm.org/doi/abs/10.1145/1159913.1159928,  你是说这种类型吗?  如果是这种类型,它属于 `inproceedings `

**Comment by zoushucai** [comment]
还有如果期刊名长度超过 80 个字符, 会被过插件滤掉, 插件内部的期刊大多数来自: https://github.com/JabRef/abbrv.jabref.org/tree/main/journals, 不过这里面有很多是错误的,要小心, 感觉也是在其他地方抓取的.  如果的确是普通期刊,可以自定义期刊缩写表..
