### ISSUE TITLE
能否添加期刊名首字母作为简称？

### ISSUE THREAD

**Issue by zhaohaiyang01** [zoushucai/zotero-journalabbr#14]
能否添加期刊名首字母作为简称？

**Comment by zhaohaiyang01** [comment]
比如Comput. Methods Appl. Mech. Eng.，简写为CMAME

**Comment by zhaohaiyang01** [comment]
> 可以呀
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年7月18日(周二) 下午5:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [zoushucai/zotero-journalabbr] 能否添加期刊名首字母作为简称？ (Issue #14) 比如Comput. Methods Appl. Mech. Eng.，简写为CMAME — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

请问怎么做到呢？原来的json和csv文件可以从哪下呢,我想直接在上面改

**Comment by zoushucai** [comment]
@zhaohaiyang01   这个需要去改源码, 源码里面的数据,我记得我写在 readme.md 中了, 或者自定义数据库就好了,

**Comment by appwcn** [comment]
查是查到了…… 怎么改呢。目前首字母缩写好像是无效的。。。

**Comment by zoushucai** [comment]
我这边好像是正确的呀
