### ISSUE TITLE
自定义缩写中如果期刊中包含逗号会报错

### ISSUE THREAD

**Issue by idvice** [zoushucai/zotero-journalabbr#15]
例如，期刊“Accounting, Organizations and Society”。

在自定义缩写文件csv，（excel打开）第一列输入“Accounting, Organizations and Society”，对应第二列输入AOE，然后保存。

使用插件自定义缩写功能就会报错“不符合要求行有(已忽略):2”

如何解决这样的问题呢？

**Comment by zoushucai** [comment]
@idvice 因为总有一个分隔符,如果一行中分隔符超过 1 个,会忽略, 此时建议用 json
