### ISSUE TITLE
期刊缩写会覆盖“其他”字段的内容

### ISSUE THREAD

**Issue by 1067237855** [zoushucai/zotero-journalabbr#16]
[zotero-journalabbr](https://github.com/zoushucai/zotero-journalabbr)：
“期刊缩写”功能会覆盖“其他”字段的内容
[zotero-pdf-translate](https://github.com/windingwind/zotero-pdf-translate)：
“标题翻译”功能是增量修改“其他”字段的内容   

希望大佬考虑一下，“期刊缩写”功能，也能够用 增量修改“其他”字段的内容

![image](https://github.com/zoushucai/zotero-journalabbr/assets/104330036/b61eec12-3712-4ccc-8ef2-a0d92f84dcfb)

**Comment by zoushucai** [comment]
@1067237855  OK 有时间搞搞, 因为 zotero7 上我自己用的插件都没更新, 我电脑都变成了 zotero6 了...

**Comment by zoushucai** [comment]
@1067237855  不对呀, 是不是你弄错了, 这两个好像没有冲突呀, '其他' 字段 只是一个中间变量,过度用的.
