### ISSUE TITLE
列设置不能自由调节

### ISSUE THREAD

**Issue by pengxy0** [zoushucai/zotero-journalabbr#17]
大佬，列设置的宽度又被固定住了，不能自由调节，可不可以看下哪里有问题，感谢
image

7.0.0-beta.36+3ef1f0992 (64-bit)
Ethereal Style：3.0.5

**Comment by zoushucai** [comment]
@pengxy0  你好呀, 我这边检查了一下, 列的宽度可以自由调节呀

**Comment by pengxy0** [comment]
那好奇怪，我把[zotero-journalabbr]开启了就不行，关闭之后就好了😂

**Comment by pengxy0** [comment]
@zoushucai 我又试了下，还是不行，现在也不知道是哪里出问题了，哎

**Comment by zoushucai** [comment]
这种原因是我忘记，如果插件关闭退出，忘记写注销脚本了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月21日(周一) 晚上6:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zoushucai/zotero-journalabbr] 列设置不能自由调节 (Issue #17)




 
那好奇怪，我把[zotero-journalabbr]开启了就不行，关闭之后就好了😂

**Comment by zoushucai** [comment]
我还在折腾git，我把源代码作者的模板合并过来，发现我的git记录乱七八糟，唉第一次合并别人的东西，学艺不精



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月21日(周一) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zoushucai/zotero-journalabbr] 列设置不能自由调节 (Issue #17)




 
@zoushucai 我又试了下，还是不行，现在也不知道是哪里出问题了，哎

**Comment by zoushucai** [comment]
@pengxy0 你的这个问题,好像不是注销引起的. 我这边注销了,标题列也消失了, 插件再次打开也能正常

**Comment by zoushucai** [comment]
我不知道你的问题在哪里

**Comment by zoushucai** [comment]
我先关闭插件,然后重启 zotero,再次打开插件, 就会出现插件没有注册的情况, 你需要重启一下 zotero 就好了, 这是因为,插件都是在启动的时候注册的, 如果 zotero 已启动, 可能插件的某些功能是无法使用

**Comment by zoushucai** [comment]
能重启解决,就重启解决

**Comment by pengxy0** [comment]
后来这几次我把插件卸掉之后，就再没出现类似的问题😀，style的大佬说，等zotero 7再接着更新，可能就好了
