### ISSUE TITLE
当前版本的 Zotero 上提示安装插件失败

### ISSUE THREAD

**Issue by jzpa** [zoushucai/zotero-journalabbr#18]
- 当前系统：`Windows 10`
- 当前 Zotero 版本：`6.0.26`
- 当前插件版本：`Releases 1.7.5`
- 安装方式：`Zotero` -> `Add-ons Manager` -> `Install Add-on From File` -> `zotero-journalabbr.xpi`
- 报错信息：
> 插件安装失败，无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

**Comment by jzpa** [comment]
似乎是因为版本适配。`Release v1.7.5` 基于的 `windingwind/zotero-plugin-template v1.0.0` 当前只支持 `Zotero 7.0.0-beta.12` 以上的版本，不过我还尝试了 `Release v0.7.0` 之后的版本，都与 `Zotero 6` 不适配，采用 `Release v0.6.14` 之后问题解决。

推荐可以在 `README` 加一下关于版本的说明。不论如何，非常感谢作者的付出！

**Comment by zoushucai** [comment]
@jzpa  是呀, Release v0.7.0 以后的不支持 Zotero 6.
