### ISSUE TITLE
在解析用户定义的 CSV 时，误以分号来分割每行（应是逗号）

### ISSUE THREAD

**Issue by Z-2ez4U** [zoushucai/zotero-journalabbr#2]
错误出自 \chrome\content\scripts\journalabbrbyzsc.js，位于129316行：var entries = csv[i].split(/;/)

**Comment by zoushucai** [comment]
不是分号吗？ csv 文件都是分号呀

**Comment by Z-2ez4U** [comment]
你记错了哟，CSV是逗号分隔的。我是用你这个运行失败才排查到的……
![image](https://user-images.githubusercontent.com/44567881/177496157-c9421a43-cf4f-4fc5-afab-929ac0fc0ebf.png)

**Comment by zoushucai** [comment]
> 你记错了哟，CSV是逗号分隔的。我是用你这个运行失败才排查到的…… ![image](https://user-images.githubusercontent.com/44567881/177496157-c9421a43-cf4f-4fc5-afab-929ac0fc0ebf.png)

是的，我记错了。 csv 文件默认是逗号分割， 由于数据库中的 csv 文件是分号，所以推荐用户导入自己的 csv 文件时，也采用分号（PS：我记得有提示呀）

<img width="389" alt="image" src="https://user-images.githubusercontent.com/15843338/177986034-919af39f-2430-408c-b899-a442c5a95573.png">

**Comment by Z-2ez4U** [comment]
嗷我理解错了，我以为你这个提示的意思是，支持用分号来同时输入多个csv路径……
