### ISSUE TITLE
会议名简写

### ISSUE THREAD

**Issue by HuimingPan** [zoushucai/zotero-journalabbr#20]
希望作者能添加一个修改会议名称简写的功能。因为会议名称很多带有年份，可能需要使用正则字符串来匹配。

**Comment by zoushucai** [comment]
我的理解,  好像同一个会议, 因为年份不同, 会议的名称也不同呀, 这是两个不同的会议

**Comment by HuimingPan** [comment]
同一个会议系列，主要只有一个年份前缀的区别。比如机器人领域的顶会 IEEE International Conference on Robotics and Automation(ICRA)，在 2010年是 “2010 IEEE International Conference on Robotics and Automation”，在2011年是 “2011 IEEE International Conference on Robotics and Automation”.

如果采用正则表达式 f"(.)* {pattern}"，就可以匹配到会议简称 "2010ICRA"
pattern 是会议名称，如 IEEE International Conference on Robotics and Automation，对应简称（ICRA）
(.)* 可以获取年份，

我希望能够在自定义刊名简写 csv/json 文件中，期刊名/会议名可以设置为正则表达式，而不是固定的字符串。虽然这对于不了解正则表达式的用户来说会有一定的学习成本，但作为一个advanced feature 还是很有用的。这可以使插件的使用范围从期刊简称拓展到会议简称，基本囊括了所有zotero 的items。

**Comment by zoushucai** [comment]
根据不同的文章类型来自定义正则表达式来缩写期刊, 是一个不错的想法.

**Comment by zoushucai** [comment]
趁周末修改了一下, 添加了正则, 可以试试
