### ISSUE TITLE
避免自动添加abbr_iso4标签

### ISSUE THREAD

**Issue by lbj-007** [zoushucai/zotero-journalabbr#21]
![image](https://github.com/zoushucai/zotero-journalabbr/assets/22144485/44ba9308-4ecc-4ad6-a556-962f6e96309e)
每次更新缩写就会在标签栏添加一个标签，有什么办法避免添加吗？

**Comment by zoushucai** [comment]
这是特意弄得的, 因为这才知道我最终选用的是哪个缩写方式.

**Comment by HuimingPan** [comment]
或许可以在设置里添加一个可以选项：自动添加标签 On/Off

**Comment by zoushucai** [comment]
新的版本可以了,推荐打个标签,不然时间久了,都不知道采用的是什么准则
