### ISSUE TITLE
添加条目时自动更新abbr

### ISSUE THREAD

**Issue by MODOUser** [zoushucai/zotero-journalabbr#22]
能否在添加条目时自动根据内置或者其他什么规则直接把简称补充上，然后再通过zotfile自动重命名和转移目录，不知道新版本是否已经支持了，我现在还在用zotero6（因为大多数在用的插件不支持），没法用本项目7.0的插件

**Comment by zoushucai** [comment]
Zotero7已支持，6的版本我已不在开发，看说明文档。对于插件来说，按需执行很重要，而不是一股脑的自动化，这样在不知情的情况下更改默认值的事情，不是很认同。对于引入别的插件，我想最近没这个计划，只做与期刊缩写相关的功能。您看看其他插件是否有类似的功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 下午5:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zoushucai/zotero-journalabbr] 添加条目时自动更新abbr (Issue #22)




 
能否在添加条目时自动根据内置或者其他什么规则直接把简称补充上，然后再通过zotfile自动重命名和转移目录，不知道新版本是否已经支持了，我现在还在用zotero6（因为大多数在用的插件不支持），没法用本项目7.0的插件

**Comment by MODOUser** [comment]
我理解您的意思，“然后再通过zotfile自动重命名和转移目录”这个是说自行操作的不是要加的新功能，整个的流程就是在期刊网站获取元数据条目之后自动补全简称，然后自己添加pdf再通过其他插件重命名的时候就可以直接使用简称了，因为我命名规则设置好了使用简称。再次感谢您的贡献，希望zotero7早点正式更新等其他插件跟进，再来使用7.0版本插件
