### ISSUE TITLE
经过多次失败后，只能伸手要dotless版本了

### ISSUE THREAD

**Issue by muzi13** [zoushucai/zotero-journalabbr#3]
我需要刊名缩写不带点的
1. 尝试了修改js脚本然后打包xpi的方法，在zotero安装插件后，点击更新缩写，无提示；
2. 尝试导入CSV文件，点击更新缩写，显示0条被更新；
无奈，限于个人水平，特请求作者提供一份缩写不带点的插件，
万分感谢！！！

**Comment by zoushucai** [comment]
csv文件默认是逗号, 不过这个插件, 采用的是分号分割

**Comment by zoushucai** [comment]
简单的改写了一下, 换了一个排序顺序, 可以试试这个, 没有经过大量测试 [不带点的](https://github.com/zoushucai/zotero-journalabbr-nodot)

**Comment by muzi13** [comment]
@zoushucai ，非常感谢你的帮助！
