### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by longzhanyuye5** [zoushucai/zotero-journalabbr#5]
作者你好
建议从英属哥伦比亚大学图书馆的网站上获取期刊缩写，https://woodward.library.ubc.ca/woodward/research-help/journal-abbreviations
每一次点击用户指定期刊缩写都需要选择位置，希望能记住位置。
插件体积较大，程序运行变慢，希望能精简一下

**Comment by zoushucai** [comment]
@longzhanyuye5   谢谢呀, 已融合改数据,  对于您提出的 体积太大的问题, 我表示无能为力, 对于记住位置,有时间想想,  不过我有一个建议, 你可以选中所有的文献, 然后再点击用户期刊缩写, 这样就完成了, 不需要一个条目一个条目的点击
