### ISSUE TITLE
如果是中文论文就看不到了

### ISSUE THREAD

**Issue by tangjyan** [zoushucai/zotero-journalabbr#7]
建议将中文论文的期刊字段赋到刊名缩写中，不然中文的都不知道什么期刊了
另外不知道可否并且将学位论文的“大学”字段显示在刊名简称中，这样能大大加强刊名简称字段的用处

**Comment by zoushucai** [comment]
> 建议将中文论文的期刊字段赋到刊名缩写中，不然中文的都不知道什么期刊了 另外不知道可否并且将学位论文的“大学”字段显示在刊名简称中，这样能大大加强刊名简称字段的用处

第一, 中文期刊添加到缩写中的意义?  
第二, 学位论文中的"大学添加 到简写期刊中的意义?
我弄这个是以前导师要求提供 bibliography 的latex, 顺势就做下去了,  如果要写带有中文的论文? 我感觉直接可以 把原有的期刊和简写交换期刊, 然后用内置的 bibtex 或者一些其他方式导出 bibtex ,   这样去弄可能更好吧,  我不知道你的用途/

**Comment by tangjyan** [comment]
> > 建议将中文论文的期刊字段赋到刊名缩写中，不然中文的都不知道什么期刊了 另外不知道可否并且将学位论文的“大学”字段显示在刊名简称中，这样能大大加强刊名简称字段的用处
> 
> 第一, 中文期刊添加到缩写中的意义? 第二, 学位论文中的"大学添加 到简写期刊中的意义? 我弄这个是以前导师要求提供 bibliography 的latex 且要求期刊简写, 顺势就做下去了, 如果要写带有中文的论文? 我感觉直接可以 把原有的期刊和简写交换期刊, 然后用内置的 bibtex 或者一些其他方式导出 bibtex , 这样去弄可能更好吧, 我不知道你的用途

我是在列表中把原本的期刊字段关了，只开了刊名缩写字段，这样可以节省空间。关了期刊字段，只有英文的能看到缩写，而中文的都不知道期刊了

**Comment by zoushucai** [comment]
> > > 建议将中文论文的期刊字段赋到刊名缩写中，不然中文的都不知道什么期刊了 另外不知道可否并且将学位论文的“大学”字段显示在刊名简称中，这样能大大加强刊名简称字段的用处
> > 
> > 
> > 第一, 中文期刊添加到缩写中的意义? 第二, 学位论文中的"大学添加 到简写期刊中的意义? 我弄这个是以前导师要求提供 bibliography 的latex 且要求期刊简写, 顺势就做下去了, 如果要写带有中文的论文? 我感觉直接可以 把原有的期刊和简写交换期刊, 然后用内置的 bibtex 或者一些其他方式导出 bibtex , 这样去弄可能更好吧, 我不知道你的用途
> 
> 我是在列表中把原本的期刊字段关了，只开了刊名缩写字段，这样可以节省空间。关了期刊字段，只有英文的能看到缩写，而中文的都不知道期刊了

看来不能实现您的需求, 我主要是方便写论文的时候导出 latex 的参考文献格式. 您这样操作感觉会污染字段.不方便以后参考文献的导出

**Comment by tangjyan** [comment]
> > > > 建议将中文论文的期刊字段赋到刊名缩写中，不然中文的都不知道什么期刊了 另外不知道可否并且将学位论文的“大学”字段显示在刊名简称中，这样能大大加强刊名简称字段的用处
> > > 
> > > 
> > > 第一, 中文期刊添加到缩写中的意义? 第二, 学位论文中的"大学添加 到简写期刊中的意义? 我弄这个是以前导师要求提供 bibliography 的latex 且要求期刊简写, 顺势就做下去了, 如果要写带有中文的论文? 我感觉直接可以 把原有的期刊和简写交换期刊, 然后用内置的 bibtex 或者一些其他方式导出 bibtex , 这样去弄可能更好吧, 我不知道你的用途
> > 
> > 
> > 我是在列表中把原本的期刊字段关了，只开了刊名缩写字段，这样可以节省空间。关了期刊字段，只有英文的能看到缩写，而中文的都不知道期刊了
> 
> 看来不能实现您的需求, 我主要是方便写论文的时候导出 latex 的参考文献格式. 您这样操作感觉会污染字段.不方便以后参考文献的导出

好的，原来需求不一样😄。打扰了
