### ISSUE TITLE
【自定义缩写】报错：不符合要求的总行数为(已忽略): 671

### ISSUE THREAD

**Issue by muzi13** [zoushucai/zotero-journalabbr#8]
插件版本：0.67；
使用自定义时，报错，如下：
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/48c7de3f-9a43-4c8d-8b25-e5e0035e532f)
CSV文件部分内容部分如下：
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/dadd05e3-a104-4260-bc25-37c70be8d732)
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/d9afa44b-c832-444f-a2dd-92ed038aca12)

请问不符合要求的行是哪个？期刊名称还有什么格式要求？

**Comment by zoushucai** [comment]
这个提示是,  你的 csv 文件一共有 671 行不符合要求,  如果在 5 行以内,会提示具体的行号, 请你检查你的 csv 的分隔符

**Comment by muzi13** [comment]
> @muzi13 这个提示是, 您的 csv 文件一共有 671 行不符合要求, 如果在 5 行以内,会提示具体的行号, 请您检查你的 csv 的分隔符, 还有您可以先少量的试试, 看看能否正确导入, 如果正确,然后在批量多次导入

您好，我尝试了只有4行的csv文件，提示第4行不符合要求，但其他符合要求的行还是不能执行缩写。如下：
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/f4c83e56-b77e-4044-92f3-b3002a66bcd0)
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/6369b326-d7dd-46c8-aadb-9d60afa7e453)
没有缩写成功不知道是什么原因呢？
请问可以的话，能否增加`.json`格式的外部文件选择。这样的话，一些名字本来就带标点符号的期刊就不会检测出来格式错误。

**Comment by zoushucai** [comment]
> > @muzi13 这个提示是, 您的 csv 文件一共有 671 行不符合要求, 如果在 5 行以内,会提示具体的行号, 请您检查你的 csv 的分隔符, 还有您可以先少量的试试, 看看能否正确导入, 如果正确,然后在批量多次导入
> 
> 您好，我尝试了只有4行的csv文件，提示第4行不符合要求，但其他符合要求的行还是不能执行缩写。如下：
> ![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/f4c83e56-b77e-4044-92f3-b3002a66bcd0)
> ![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/6369b326-d7dd-46c8-aadb-9d60afa7e453)
> 没有缩写成功不知道是什么原因呢？
> 请问可以的话，能否增加`.json`格式的外部文件选择。这样的话，一些名字本来就带标点符号的期刊就不会检测出来格式错误。

我不建议您excel 打开csv文件，你用文本编辑器打开csv文件，看看分隔符是什么？ 因为插件的默认分隔符为分号（；），如果是excel打开csv默认的是逗号（，）所以要锁定你的分隔符是什么。我建议还是用分号作为默认分隔符，这样可以防止某些期刊带特殊标点

**Comment by muzi13** [comment]
按照上述做法，修改分隔符为`;`，用文本文档编辑后另存为csv文件，UTF-8编码，没有用excel打开，还重启了zotero软件，结果还是不行，显示：0/1已缩写。
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/dd69c431-acf9-4e29-a381-5a0f1cf873da)

下面是用quicklook预览的文件内容：
TXT
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/3c0e2145-b3ca-4400-bf9b-6c5c2c9336c8)
CSV
![image](https://github.com/zoushucai/zotero-journalabbr/assets/44488800/a9ff97d1-b13a-412e-826f-490f6d138a06)
不知道我的操作有问题没？

**Comment by muzi13** [comment]
当然，我需要自定义缩写的期刊名称，包含在设置的csv文件中。

**Comment by zoushucai** [comment]
> 按照上述做法，修改分隔符为`;`，用文本文档编辑后另存为csv文件，UTF-8编码，没有用excel打开，还重启了zotero软件，结果还是不行，显示：0/1已缩写。 ![image](https://user-images.githubusercontent.com/44488800/238123271-dd69c431-acf9-4e29-a381-5a0f1cf873da.png)
> 
> 下面是用quicklook预览的文件内容： TXT ![image](https://user-images.githubusercontent.com/44488800/238123227-3c0e2145-b3ca-4400-bf9b-6c5c2c9336c8.png) CSV ![image](https://user-images.githubusercontent.com/44488800/238123088-a9ff97d1-b13a-412e-826f-490f6d138a06.png) 不知道我的操作有问题没？

只要没有报错,基本上可以认为输入符合要求.  
其中0/1 的含义是,  分母 表示您选择了多少个文献条目,  分子表示您使用数据库对期刊简写字段操作成功的条目, 比如这里 0/1 表示您只选择了一个条目, 0 表示只有 0 篇文章进行了期刊简写.

**Comment by muzi13** [comment]
谢谢回复，不过目前没有解决我的问题。
祝愿以后的版本越来越好。
