### ISSUE TITLE
自定义缩写失效

### ISSUE THREAD

**Issue by appwcn** [zoushucai/zotero-journalabbr#9]
1. 使用excel建立”0期刊缩写.csv“文件，第一列为期刊名，第二列为缩写
2. 在设置中，指定路径下的”0期刊缩写.csv“文件
3. 点击期刊缩写->自定义缩写，显示”0/x已缩写“

**Comment by lishuzhong123** [comment]
+1，也是碰到了这个问题，把util.ts的268行的.toLowerCase()删掉也不行，测不动了😥，求好心人解答

**Comment by zoushucai** [comment]
@appwcn  @lishuzhong123 始终不建议用 excel 打开 csv, 且 csv 默认的好像是逗号分隔, 这个插件用的是分号, 我不清楚您们的具体期刊简写表是怎么回事, 有时间的话,请给我一个你的期刊简写图以及运行的结果....   (还有可以试试预发布版本,  一会上传, 最近没时间,  前端时间写了一个添加 json的, 不知道有没有问题, 没有进一步测试)

**Comment by appwcn** [comment]
好的，尽管是excel创建，但使用vs code修改。
我先看下json是否可以解决。如果不能，再来答复。

**Comment by appwcn** [comment]
> @appwcn @lishuzhong123 始终不建议用 excel 打开 csv, 且 csv 默认的好像是逗号分隔, 这个插件用的是分号, 我不清楚您们的具体期刊简写表是怎么回事, 有时间的话,请给我一个您的期刊简写图以及运行的结果. 可以试试最新的预发布版本, 支持 json 自定义期刊文件(测试的比较少)

@zoushucai 
1. chrome/content/scripts/目录下没有找到journalabbrbyzsc.js文件，仅看到index.js。修改它可以解决。
2. 新版本自定义仍无效。
- 如果文件是逗号分隔，显示“0/x已缩写”
Quarterly Journal of Economics,QJE
Journal of Political Economy,JPE
Journal of Environmental Economics and Management,JEEM
American Economic Review,AER
- 如果文件是分号分隔，显示“不符合样式的总行数行为（已忽略）”
Quarterly Journal of Economics;QJE
Journal of Political Economy;JPE
Journal of Environmental Economics and Management;JEEM
American Economic Review;AER

**Comment by zoushucai** [comment]
@appwcn  1, 由于采用了新的模板, journalabbrbyzsc.js 已经变成了index.js
2. 这个问题我已修复,可以试试最新版,测试测试, 记得测试的时候都可以, 后面居然遗忘了关键词 await.

**Comment by muzi13** [comment]
0.6.9版本的自定义缩写功能确实可以用了，使用csv和json都可以，以前的版本应该是有问题的 #8 。
不过新版本还是有个小问题：当期刊名全称只有一个词时，即缩写与全称相同的情况下，不管是内置缩写还是自定义缩写，即使提示1/1已缩写，刊名简称处都无反应。
例如：
{
    "Measurement": "Measurement",
    "Sensors": "Sensors"
}

**Comment by zoushucai** [comment]
Ok 明天看看,

**Comment by appwcn** [comment]
好的，那我关掉～
